[package]
name = "saving_and_updates"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }
hecs = {version = "0.10.5", features = ["serde"] }

strum_macros = "0.26.4"
